import { app, type HttpRequest, type HttpResponseInit, type InvocationContext } from "@azure/functions";
import { z } from "zod";
import { requireAuth, requireRole } from "../auth.js";
import { query, transaction } from "../db.js";
import { errorResponse, HttpError, json, parseJson } from "../http.js";

async function admin(request: HttpRequest) { const user = await requireAuth(request); requireRole(user, "Admin"); return user; }
const admissionNumber = /^BM-\d{4}-\d{4}$/;
const reviewSchema = z.discriminatedUnion("decision", [
  z.object({ decision: z.literal("approve"), admissionNumber: z.string().regex(admissionNumber) }),
  z.object({ decision: z.literal("reject"), reason: z.string().trim().min(3).max(500) }),
  z.object({ decision: z.literal("reopen") }),
]);
const courseSchema = z.object({ code: z.string().trim().min(2).max(30), title: z.string().trim().min(2).max(160), description: z.string().trim().max(3000).default(""), duration: z.string().trim().max(80).default(""), status: z.enum(["draft","active","archived"]).default("draft") });
const enrollmentSchema = z.object({ studentIds: z.array(z.string().uuid()).min(1).max(250) });
const progressSchema = z.object({ progress: z.number().int().min(0).max(100), status: z.enum(["enrolled","in_progress","completed","withdrawn"]), notes: z.string().max(2000).default("") });
const campaignSchema = z.object({ title: z.string().trim().min(2).max(160), message: z.string().trim().min(2).max(10000), category: z.string().trim().max(80).default("Platform update"), priority: z.enum(["normal","important","urgent"]).default("normal"), userIds: z.array(z.string().uuid()).max(1000).optional(), all: z.boolean().default(false), publishAt: z.string().datetime().optional(), expiresAt: z.string().datetime().optional() });

async function listAdmissions(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> { try { await admin(request); const r=await query(`SELECT id,academy_id,full_name,admission_id,admission_number,status,rejection_reason,created_at,reviewed_at FROM user_profiles WHERE role <> 'admin' ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,created_at DESC`); return json(200,{data:r.rows}); } catch(e){ return errorResponse(e,context.invocationId); } }
async function reviewAdmission(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> { try { const a=await admin(request); const input=await parseJson(request,reviewSchema); const row=await transaction(async c=>{ const found=await c.query(`SELECT id FROM user_profiles WHERE id=$1 AND role<>'admin' FOR UPDATE`,[request.params.id]); if(!found.rowCount) throw new HttpError(404,"Student not found."); if(input.decision==="approve"){ const r=await c.query(`UPDATE user_profiles SET status='active',admission_number=upper($1),reviewed_by=$2,reviewed_at=now(),rejection_reason=NULL,updated_at=now() WHERE id=$3 RETURNING *`,[input.admissionNumber,a.profileId,request.params.id]); return r.rows[0]; } if(input.decision==="reject"){ await c.query(`UPDATE auth_sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL`,[request.params.id]); const r=await c.query(`UPDATE user_profiles SET status='rejected',rejection_reason=$1,reviewed_by=$2,reviewed_at=now(),updated_at=now() WHERE id=$3 RETURNING *`,[input.reason,a.profileId,request.params.id]); return r.rows[0]; } const r=await c.query(`UPDATE user_profiles SET status='pending',rejection_reason=NULL,reviewed_by=$1,reviewed_at=now(),updated_at=now() WHERE id=$2 RETURNING *`,[a.profileId,request.params.id]); return r.rows[0]; }); return json(200,{data:row}); } catch(e){ return errorResponse((e as {code?:string}).code==="23505"?new HttpError(409,"Admission number is already assigned."):e,context.invocationId); } }
async function listCourses(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit>{ try{ await admin(request); const r=await query(`SELECT c.*,count(e.id)::int enrollment_count,count(e.id) FILTER(WHERE e.status='completed')::int completion_count FROM courses c LEFT JOIN course_enrollments e ON e.course_id=c.id GROUP BY c.id ORDER BY c.created_at DESC`); return json(200,{data:r.rows}); }catch(e){return errorResponse(e,context.invocationId);} }
async function createCourse(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit>{ try{const a=await admin(request),i=await parseJson(request,courseSchema); const r=await query(`INSERT INTO courses(code,title,description,duration,status,created_by) VALUES(upper($1),$2,$3,$4,$5,$6) RETURNING *`,[i.code,i.title,i.description,i.duration,i.status,a.profileId]);return json(201,{data:r.rows[0]});}catch(e){return errorResponse(e,context.invocationId);} }
async function enroll(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit>{try{await admin(request);const i=await parseJson(request,enrollmentSchema);const r=await query(`INSERT INTO course_enrollments(course_id,student_id) SELECT $1,unnest($2::uuid[]) ON CONFLICT(course_id,student_id) DO NOTHING RETURNING *`,[request.params.id,i.studentIds]);return json(201,{data:r.rows});}catch(e){return errorResponse(e,context.invocationId);} }
async function updateEnrollment(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit>{try{await admin(request);const i=await parseJson(request,progressSchema);const r=await query(`UPDATE course_enrollments SET progress=$1,status=$2,notes=$3,completed_at=CASE WHEN $2='completed' THEN coalesce(completed_at,now()) ELSE NULL END,updated_at=now() WHERE id=$4 RETURNING *`,[i.progress,i.status,i.notes,request.params.id]);if(!r.rowCount)throw new HttpError(404,"Enrollment not found.");return json(200,{data:r.rows[0]});}catch(e){return errorResponse(e,context.invocationId);} }
async function createCampaign(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit>{try{const a=await admin(request),i=await parseJson(request,campaignSchema);if(!i.all&&!i.userIds?.length)throw new HttpError(400,"Choose at least one recipient.");const data=await transaction(async c=>{const campaign=await c.query(`INSERT INTO notification_campaigns(title,message,category,priority,publish_at,expires_at,created_by) VALUES($1,$2,$3,$4,coalesce($5::timestamptz,now()),$6,$7) RETURNING *`,[i.title,i.message,i.category,i.priority,i.publishAt||null,i.expiresAt||null,a.profileId]);await c.query(`INSERT INTO notification_recipients(campaign_id,user_id) SELECT $1,id FROM user_profiles WHERE role<>'admin' AND status='active' AND ($2::boolean OR id=ANY($3::uuid[]))`,[campaign.rows[0].id,i.all,i.userIds||[]]);return campaign.rows[0];});return json(201,{data});}catch(e){return errorResponse(e,context.invocationId);} }
async function verifyCertificate(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit>{try{const r=await query(`SELECT verification_number,student_name,course_title,completion_date,issued_at,status FROM certificates WHERE verification_number=$1 AND status IN('issued','revoked')`,[request.params.number]);if(!r.rowCount)throw new HttpError(404,"Certificate not found.");return json(200,{data:r.rows[0]});}catch(e){return errorResponse(e,context.invocationId);} }

app.http("adminAdmissions",{route:"v1/admin/admissions",methods:["GET"],authLevel:"anonymous",handler:listAdmissions});
app.http("adminReviewAdmission",{route:"v1/admin/admissions/{id:guid}/review",methods:["POST"],authLevel:"anonymous",handler:reviewAdmission});
app.http("adminCourses",{route:"v1/admin/courses",methods:["GET","POST"],authLevel:"anonymous",handler:async(r,c)=>r.method==="POST"?createCourse(r,c):listCourses(r,c)});
app.http("adminEnroll",{route:"v1/admin/courses/{id:guid}/enrollments",methods:["POST"],authLevel:"anonymous",handler:enroll});
app.http("adminUpdateEnrollment",{route:"v1/admin/enrollments/{id:guid}",methods:["PATCH"],authLevel:"anonymous",handler:updateEnrollment});
app.http("adminCreateCampaign",{route:"v1/admin/notifications",methods:["POST"],authLevel:"anonymous",handler:createCampaign});
app.http("verifyCertificate",{route:"v1/certificates/verify/{number}",methods:["GET"],authLevel:"anonymous",handler:verifyCertificate});
